# Generated by Django 6.0 on 2026-05-03 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NewUsers",
            new_name="NewsUsers",
        ),
    ]
