# Generated by Django 6.0 on 2026-05-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_rename_newusers_newsusers"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsusers",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="newsusers",
            name="verify_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="newsusers",
            name="verify_code_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
